name: Asian Economic Development Association
favicon: null
layout_spectrum: 0.6965079752262682
typography_spectrum: 0.10217105527408421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0084ca'
    - '#231f20'
    - '#97cbe9'
    - '#626365'
  brandStrength: 0.09301982540637255
  lightness: 0.13504351605661213
  saturation: 0.8019049339927733
  rhythmicContrast: 0.20654493244364858
purpose: []
