name: Asian Economic Development Association
favicon: null
layout_spectrum: 0.6965079752262682
typography_spectrum: 0.10217105527408421
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#0084ca'
    - '#231f20'
    - '#97cbe9'
    - '#626365'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
